name: Publish Installer

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21

      - name: Build Installer
        run: nix build .#default

      - name: Prepare Artifact
        run: cp result/installer.sh ./installer.sh

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: installer.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
